# Generated by Django 5.2.4 on 2025-07-28 11:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitreminder',
            name='reminder_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
