# Generated by Django 5.2.4 on 2025-07-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Developer', 'Developer'), ('Manager', 'Manager')], default='Developer', max_length=20),
        ),
    ]
