# Generated by Django 5.2.4 on 2025-07-24 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_passwordreset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='name',
            new_name='Habit_name',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='user',
        ),
    ]
