# Generated by Django 5.2.4 on 2025-07-24 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_rename_name_habit_habit_name_remove_habit_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='Habit_name',
            new_name='name',
        ),
    ]
