name: Habit Tracker Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    env:
        ENVIRNMENT : development
        SECRET_KEY : SECRET_KEY
        ENCRYPT_KEY : UqMKrgNqUnyz6ha3XJVE6qqNKkf7zvvyfV-D7gqXN6U=

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run migrations and tests
      run: |
        python manage.py makemigrations --noinput
        python manage.py migrate --noinput
        python manage.py test
